version: '3.4'

services:
  app:
    image: elimbatido/koiner-dapp
    build:
      context: ./
      dockerfile: Dockerfile
      target: production-stage-spa
    volumes:
      - app:/app
    ports:
      - "9000:80"

volumes:
  app:

networks:
  default:
