export const contractsMap: Record<string, string> = {
  '1HGN9h47CzoFwU2bQZwe6BYoX4TM6pXc4b': 'Koinos Resources',
  '19qj51eTbSFJYU7ZagudkpxPgNSzPMfdPX': 'Koinos Governance',
  '15DJN4a8SgrbGhhGksSBASiSYjGnMU8dGL': 'Koin',
  '159myq5YUhhoVWu3wsHKHiJYKPKGUrGiyv': 'Koinos Proof-of-Burn',
  '18zw3ZokdfHtudzaWAUnU4tUvKzKiJeN76': 'Koinos Claim Koin',
  '19WxDJ9Kcvx4VqQFkpwVmwVEy1hMuwXtQE': 'Koinos Nameservice',
  '1AdzuXSpC6K9qtXdCBgD5NUpDNwHjMgrc9': 'VHP [deprecated]',
  '18tWNU7E4yuQzz7hMVpceb9ixmaWLVyQsr': 'VHP',

  // '': '',

  '15zQzktjXHPRstPYB9dqs6jUuCUCVvMGB9': 'Bitcoin [Chainge]',
  '15twURbNdh6S7GVXhqVs6MoZAhCfDSdoyd': 'Ethereum [Chainge]',
  '14MjxccMUZrtBPXnNkuAC5MLtPev2Zsk3N': 'Tether USD [Chainge]',

  '1Cg38hAHSFK9DynwMsbHUmP7EzeXSxy86o': 'KoinDX KOIN-ETH Staking Pool',
  '1FVmM3DoNeFvif4qFVBHm6BqMNMiDSigMu': 'KoinDX KOIN-VHP Staking Pool',
  '12X3zJ71EwmCsYhnbvsrUUkTB9LjWkvPUL': 'KoinDX KOIN-USDT Staking Pool',
  '1Ht9gnbiRLPsAJj7atQUC67LJzBL3cEuuR': 'KoinDX KOIN-BTC Staking Pool',
  '19DpgtbBqc5mpENEPiKvMQMvY9UWtmQj5X': 'KoinDX Points',

  '16tsFkc5RyuwQmXxVABzHHwS513Nu2B9S3': 'Kollection',
  '1AyXgogBeFG9XSJjpSBFujNcfXbo8cbrKE': 'Kollection',
  '17e1q6Fh5RgnuA8K7v4KvXXH4k9qHgsT5s': 'KoinDX V2',
  '14WeQjBk7F4C58xUquRGLK1KiqRjwj5Y4J': 'KoinDX V1',
  '1A4Nv58odXgVK91bFHgCFWPgiu7kfsxdVY': 'Lords Forsaken Packs',
  '18krVkBnkgVqGb6vbxCjVi1DS6zru1ojDG': 'Lords Forsaken Cards',
  '1LeWGhDVD8g5rGCL4aDegEf9fKyTL1KhsS': 'Kanvas',
  '13tmzDmfqCsbYT26C4CmKxq86d33senqH3': 'KAP',
  '1D53GFQkL5TkQ9okuf6r3Gta3oeTMVgGJW': 'KAP USD Oracle',
  '1EttfMuvTXGh8oE6vLiRF5JfqBvRiofFkB': 'KAP Profile',
  '1KD9Es7LBBjA1FY3ViCgQJ7e6WH1ipKbhz': 'Nicknames',
  '18jxgZrAmpsyYkE9Exi6xJdtU44epxegVZ': '@FREEMANA',
  '162GhJwsciDiKsgwzj2t6VoFHt3RMzGKdG': 'Koinos Box Mana sharer',

  '1EF5oQHJPmUFnVwEdLmHxsiuv3Gvuzrymh': 'Kuku Pool, @kuku-eth-usd-900',
  '1PvAfM8CEnhLnkYsK4vMbNeHUK86Y6KsUB': 'Kuku Pool, @kuku-btc-usd-14400',
  '1a8wVRRRhRD6iYceuVyyYcCPgCZGpH3nx': 'Kuku Pool, sol-usd',
  '1GMQ31cCuwzzkL7tMzaEk4VzAWqe2mNm7i': 'Kuku Pool, @kuku-btc-usd-3600',
  '1NGmGtQZ2HEjzsVr16FX7Tab7jM98FWmEy': 'Kuku Playing Cards',
  '1MgPGutcKgUPsVJH3zR8kVfDr6rr6mwuae': 'OTC Offers',

  '1NsQbH5AhQXgtSNg1ejpFqTi2hmCWz1eQS': 'BurnKoin',
  '15jueaBcMieDCMGw6wAmEK6cNSUVicknG1': "Koinnoisseur's max VAPOR pool",
  '1DGNQQimsyBQajzQdWXY96m84YyDC2pUpB': 'JGA Pool #1',
  '13iFaqgdnsoqUTCwZC9GtRXwh8ZvdiiPwm': 'Engrave development sponsorship pool',
  '18DmHs6kCnr4E9Rr2Hcvm3YfXhiQ9wBuNq': 'Freedom Pool',
  '1MFXTiWWGGhrCzGsH5TJ9x1zRyN8sNwYPr': 'OnKoinos (made in Australia)',
  '14iHqMGBznBM7xJXhkrQ266FgoFdymCqLM': 'KoinForge',
  '1KfD7n93LnnihyygopWUVTkbtWVe5aXXGW': 'Koinos en español',
  '1MbsVfNw6yzQqA8499d8KQj8qdLyRs8CzW': 'JGA Pool #2',
  '1GJxaZw2BPU7NhB7fuVGKfQxaQ3tkhVKb8':
    "Koinnoisseur's quick KOIN restore pool",
  '1DWpSxntZbLU9HvGDPkSqdKrVvNRoUwAis': 'AlgoScout',
  '18UYKhWVCbTpFs8oYC54xoiCQQthhEkX7m': "Koinnoisseur's max VHP pool",
  '1EPZaqve43k9Jq5mNeT2ydCjUiytTTU4U': 'Koinos Group Fogata BP',
  '1932QKYoPzaGmwBxTnnYhNqV9LQi2sYLHT': 'Suspicious Mainnet Pool',

  '1AhGbSHUVaTWV1oqJRSTihsi2ofEvvYevg': 'Koincity Moon Boys',
  '1B7qbYg5TuHULf2Q5LjHLUEMRR8ofCFUS2': 'Koincity Mutant Boys',
  '1FZnS98QunDkzVjMz4G8BRSTAZyYCaPHhm': 'Koincity Launchpad',
  '1JpcbhG3PtPyDS8yumjoBC4EPHnN9tQVwQ': 'Koincity Staking Pools',
  '1FcqYLePAujdkEkLRoQqH7HU1AEQLpSS7D': 'KoinCity Orders',

  // Exchanges
  '1LNFGjYybk5EvPCssAmPNSCRC5LYxv81Kb': 'MEXC',
  '16oKBPiApEhjaoEGULwAouA11QckHQ1oZJ': 'Coinstore',
  // '': 'Biconomy',
  // '': 'LCX',
};
